"""productInfoTable deploy에 index 설정

Revision ID: 1a6f9b35ef04
Revises: 56602a8479d3
Create Date: 2023-11-16 21:18:50.147536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6f9b35ef04'
down_revision: Union[str, None] = '56602a8479d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_info_deploy'), 'product_info', ['deploy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_deploy'), table_name='product_info')
    # ### end Alembic commands ###
