"""productInfoTable에 deploy 컬럼 생성

Revision ID: 56602a8479d3
Revises: e542f9af62ee
Create Date: 2023-11-16 21:04:28.711906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56602a8479d3'
down_revision: Union[str, None] = 'e542f9af62ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_history', 'payment_info',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('order_row', 'delivery_company',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('order_row', 'delivery_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('product_info', sa.Column('deploy', mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'deploy')
    op.alter_column('order_row', 'delivery_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('order_row', 'delivery_company',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('order_history', 'payment_info',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
