"""full text index 설정

Revision ID: 9f13a5fbbbe8
Revises: a3e3ea5eca5b
Create Date: 2023-12-03 13:45:01.799182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f13a5fbbbe8"
down_revision: Union[str, None] = "a3e3ea5eca5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_search_info",
        "product_info",
        ["search_info"],
        unique=False,
        mysql_length=255,
        mysql_prefix="FULLTEXT",
        mysql_with_parser="ngram",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_search_info",
        table_name="product_info",
        mysql_length=255,
        mysql_prefix="FULLTEXT",
        mysql_with_parser="ngram",
    )
    # ### end Alembic commands ###
