"""productInfoTable product_id unique설정

Revision ID: a3e3ea5eca5b
Revises: de752a5b9bac
Create Date: 2023-11-17 18:17:39.607496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e3ea5eca5b'
down_revision: Union[str, None] = 'de752a5b9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_product_id_uc', 'product_info', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_product_id_uc', 'product_info', type_='unique')
    # ### end Alembic commands ###
