"""productInfoTable price_desc_cursor, price_asc_cursor에 inex 설정

Revision ID: de752a5b9bac
Revises: 1a6f9b35ef04
Create Date: 2023-11-17 11:22:06.446779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de752a5b9bac'
down_revision: Union[str, None] = '1a6f9b35ef04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_info_price_asc_cursor'), 'product_info', ['price_asc_cursor'], unique=False)
    op.create_index(op.f('ix_product_info_price_desc_cursor'), 'product_info', ['price_desc_cursor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_price_desc_cursor'), table_name='product_info')
    op.drop_index(op.f('ix_product_info_price_asc_cursor'), table_name='product_info')
    # ### end Alembic commands ###
