"""user table email_verification colum을 last_login column으로 전환

Revision ID: f6f2cb9b151a
Revises: 
Create Date: 2023-12-06 22:19:42.993643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6f2cb9b151a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'email_verification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
