name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: check location
        run: |
          pwd

      - name: connect to aws cl
        run: |
          ssh -i ~/.ssh/dodo-instance.pem ubuntu@13.124.238.182 "pwd && ls -a && docker --version"
