name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ main ]

env:
  DOCKER_LOCAL: docker-compose -f docker_compose_staging_build.yml
  DOCKER_SERVER: docker-compose -f docker_compose_staging_server.yml


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: docker-compose build and push
        run: |
             cd /Users/yangwoolee/repo/captured/docker 
             docker-compose -f docker_compose_staging_build.yml build
             ${{ env.DOCKER_LOCAL }} push
      - name: docker-compose 
        run: |
              ssh -i ~/.ssh/dodo-instance.pem ubuntu@13.124.238.182 "cd captured
              ${{ env.DOCKER_SERVER }} down
              ${{ env.DOCKER_SERVER }} pull
              ${{ env.DOCKER_SERVER }} up -d"
